# Numpy Arrays

In [1]:
import numpy as np
type(np.array(["Tanzir", 2, 3]))
# data type has changed from the list to an array
# also ndarray stands for n dimensional array

numpy.ndarray

# Upcasting

In [2]:
np.array([1,2,3.0])
# 2 elements were integer and one was float but after using array it made all of them a float element

array([1., 2., 3.])

# Two Dimensions

In [3]:
np.array([[1,2,3],
          [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array([1,2,3], ndmin=5) #ndmin stands for number of minimum dimensions

array([[[[[1, 2, 3]]]]])

In [5]:
# dtype

In [6]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
random_array = np.array([(1,0),
                       (3,4)])
random_array

array([[1, 0],
       [3, 4]])

**In above numpy array the location of 1 is (0,0) and that of 0 is (0,1) and that of 3 is (1,0) and that of 4 is (1,1)**

### Now i am going to access the data from the numpy array that i have already made.

In [8]:
random_array[0][0]

1

In [9]:
random_array[0][1]

0

In [10]:
random_array[1][1]

4

In [11]:
random_array[1][0]

3

In [12]:
# Below we're trying to map one variable with other so in (1,2) 1 is a and 2 is b similarly in (3,4) 3 is a and 4 is b

In [13]:
x = np.array([(1,2),(3,4)], dtype = [('a', '<i2'), ('b', '<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [14]:
# Again we'll extract the data from above numpy array
x[1][0]

3

In [15]:
type(x[1][0])

numpy.int16

The data type present on the x cordinate will be **int16** as i can see and it's because of **dtype = [('a', '<i2'), ('b', '<i8')]**

In [16]:
type(x[0][1])

numpy.int64

The data type present on the y coordinate will be **int64** as i can this and this is because of **dtype = [('a', '<i2'), ('b', '<i8')]**

If i change the vaule as **i4** in **('b','<i8')** it will change the type of the values as well

# Matrices

Matrix is another data type in terms of a numpy it's a subset of array.

In [17]:
matix = np.mat(np.array([[1,2],[4,7]]))

In [18]:
type(matix)

numpy.matrix

I can even pass string and in output get matrix as an output

In [19]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [20]:
# I can also convert list into a matrix
np.mat([1,2])

matrix([[1, 2]])

In [21]:
# Now i will be passing list of list
np.mat([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

# numpy.asarray

In [22]:
# here we have a list
a = [1,2]
type(a)

list

In [23]:
# Here we're converting our list as a numpy array
type(np.asarray(a))

numpy.ndarray

In [24]:
#Similarly
b = [[1,2],[3,4]]
b

[[1, 2], [3, 4]]

In [25]:
type(np.asarray(b))

numpy.ndarray

In [26]:
# Both numpy array and numpy asarray try to convert the data into an array

In [27]:
# As we have converted our data in numpy array we would easily be able to do the same in numpy asarray as well
a = np.array([1,2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [28]:
np.asarray([1,2]) is a

False

The function below is not usefull at all it's used for comparison only 

In [29]:
issubclass(np.matrix, np.ndarray)

True

In [30]:
issubclass(np.ndarray,np.matrix)

False

so matrix is a sub class of numpy array but numpy array is not a subclass of matrix

# asanyarray()

In [31]:
a = [1,2]
np.asanyarray(a)
type(np.asanyarray(a))

numpy.ndarray

My original list has been converted as an ndarray

In [32]:
a = np.matrix([[1,2]])
np.asanyarray(a)

matrix([[1, 2]])

In [33]:
a = np.matrix([1,2])
a

matrix([[1, 2]])

Now i have a matrix and matrix is already a subclss of array so it will not convert the matrix into an array 

In [34]:
# Here is the proff of above statement mu np.asanyarray is same as my matrix array
np.asanyarray(a) is a

True

In [35]:
# But if i write np.array(a) or np.asarray() it will convert my matrixes into an array but .asanyarray(a) wont do that
type(np.array(a))

numpy.ndarray

In [36]:
type(np.asarray(a))

numpy.ndarray

So remember
* np.array(a)
* np.asarray(a)  # will convert any metrixes in any array
* np.asanyarray(a) # won't convert any matrixes as any array

# numpy.copy

In [37]:
np.array(a, copy=True)

array([[1, 2]])

In [38]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [39]:
y = x
y

array([1, 2, 3])

we had an numpy array called x that had some value then we said that y=x so what happened in the backend is that in the internal memory y was not alloted it's own space but it was meearly pointing towards the direction of x. so if i do some manipulation in x that manipulation will be refrected in y as well and vice versa

In [40]:
# So initially the value of y at location 1 was 2
print(f"The original value of y[1] is: {y[1]}")
# Now
y[1]=3223424
print(f" The new value of at the location y[1]: {y[1]} and the y array is like {y}")
print(f"The value of x at the 1st index is: {x[1]} and the new x array is like {x}")

The original value of y[1] is: 2
 The new value of at the location y[1]: 3223424 and the y array is like [      1 3223424       3]
The value of x at the 1st index is: 3223424 and the new x array is like [      1 3223424       3]


So i can clearly see the values have been in the x as well even though the manipulation i did was on y only **this manipulation will work the other way around as well**

In [41]:
z = np.copy(x)
z

array([      1, 3223424,       3])

In [42]:
# So initially the value of y at location 1 was 2
print(f"The original value of y[1] is: {x[1]}")
# Now
z[1] = 111
print(f" The new value of at the location y[1]: {z[1]} and the y array is like {z}")
print(f"The value of x at the 1st index is: {x[1]} and the new x array is like {x}")

The original value of y[1] is: 3223424
 The new value of at the location y[1]: 111 and the y array is like [  1 111   3]
The value of x at the 1st index is: 3223424 and the new x array is like [      1 3223424       3]


Now i can clearly see that the value of x did not changed even though i made some changes on x this is because the .copy() alots a different set of memory and it's not pointing in the same direction which is what happened in the previous scenarion

np.copy() is a function that creates a **deep copy operation** of the function while when we do w=z it created a **swallow copy operation**

# Answers of the questions
* **np.mat and np.matrix are both same**
* **Array is available in numpy package while list is not available in numpy package which is why they are different in the context of the numpy**

# **NUMPY numpy.fromfunction()**

**lambda function:** It's an anonymous function that takes parameters and perform some tasks

In [43]:
np.fromfunction(lambda i, j: i==j, (3,3), dtype=int) # here lambda function is taking two inputs and checking if i==j or not.
#REMEMBER i AND j THE VALUES OF THE INDEXES FOR A 3x3 MATRIX

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [44]:
np.fromfunction(lambda i,j,k: i*j*k, (3,3,3), dtype=int) # This used the same logic as from above and gives an output but in 3 dimensional array

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

and just like me moved from 2 to 3 we can go from any dimensions for the representation purposes

In [45]:
np.fromfunction(lambda i,j,k,l: i*j*k*l, (3, 3,3,3), dtype=int)

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]]])

(3, 3,3,3) basically means that we have (3,3,3) matrics 3 times.

In [46]:
np.fromfunction(lambda i,j,k,l: i*j*k*l, (10, 3,3,3), dtype=int)

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  3,  6],
         [ 0,  6, 12]],

        [[ 0,  0,  0],
         [ 0,  6, 12],
         [ 0, 12, 24]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]],

**similarly above we have (3,3,3) matrix 10 times**

In [47]:
np.fromfunction(lambda i,j,k,l: i*j*k*l, (1, 3,3,3), dtype=int)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

here we have (3,3,3) data 1 times

that initial value that we had which kept on change that went from 3 to 10 to 1 that value is our 
**dimensions**

Below going to give me the output as an object of the generator

In [48]:
iterables = (x*x for x in range(5))
iterables

<generator object <genexpr> at 0x000001A4ECAA2500>

### np.fromiter(variable, dtype)

In [49]:
np.fromiter(iterables, float)

array([ 0.,  1.,  4.,  9., 16.])

In [50]:
# what we have above can be performed on list as well

### np.fromstring("Some String", sep = " ")

 ###  ***sep*** stands for  ***saperator*** so our string got separated based on the separater argument we provided

In [51]:
a = np.fromstring('234 234', sep=" ")
a

array([234., 234.])

In [52]:
# Another Example
np.fromstring('1,2', sep = ',')

array([1., 2.])

**How to create a record array from a (flat) list arrays**

In [53]:
x1 = np.array([1,2,3,4])

In [54]:
x2 = np.array(['rr','sfdf','fd','re'])

In [55]:
x3 = np.array([1.1,2,3,4])
x4 = np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [56]:
r = np.core.records.fromarrays([x1,x2,x3,x4], names='a,b,c,d')
r

rec.array([(1, 'rr', 1.1, 1.1), (2, 'sfdf', 2. , 2. ),
           (3, 'fd', 3. , 3. ), (4, 're', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U4'), ('c', '<f8'), ('d', '<f8')])

so above function basically created this tuple where our values are like (x1,x2,x3,x4) 

In [57]:
r[1]

(2, 'sfdf', 2., 2.)

In [58]:
r[1]['b']

'sfdf'

In [59]:
r[1]['a']

2

# data type

In [60]:
my_list = [1,2,3]
arr = np.array(my_list)

In [61]:
arr

array([1, 2, 3])

In [62]:
type(arr)

numpy.ndarray

In [63]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat  = np.array(my_mat)
print(f"Type of this matrix is :{type(mat)}")
print(f"Here is the martic: {mat}")
print("Dimension of this metrix is :", mat.ndim, sep='') #dimension of the array is a 2-D array
print("Size of this metrix", mat.size, sep='') # Size gives the total number of elements
print("Shape of the metrix:", mat.shape, sep='') #Number of elements along each axes
print("Data type of this metrix:", mat.dtype, sep='') #dtype gives the data type contained in the array

Type of this matrix is :<class 'numpy.ndarray'>
Here is the martic: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of this metrix is :2
Size of this metrix9
Shape of the metrix:(3, 3)
Data type of this metrix:int32


we use these to debug our code which we will need plenty in deep learning

In [64]:
my_mat = [[1.1,2,3],[4,5.5,6],[7,8.8,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype, sep='')
print("\n\n Even tuples can be converted to ndarrays...")

Data type of the modified matrix: float64


 Even tuples can be converted to ndarrays...


In [65]:
b = np.array([(1,1.5,6), (2,6,9)])
print("this matrix is made from tuple not a list")
print(b)

this matrix is made from tuple not a list
[[1.  1.5 6. ]
 [2.  6.  9. ]]


# arange

In [66]:
# in python this is how range worked
list(range(5,50,2))

[5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49]

In [67]:
# We cant pass a float in python range
list(range(4,40,2.2))

TypeError: 'float' object cannot be interpreted as an integer

In [68]:
# For numpy
np.arange(5,16,2)

array([ 5,  7,  9, 11, 13, 15])

In [69]:
# But numpy works for float values as well
np.arange(5,15,0.8) # 0.8 was a step

array([ 5. ,  5.8,  6.6,  7.4,  8.2,  9. ,  9.8, 10.6, 11.4, 12.2, 13. ,
       13.8, 14.6])

***This is the only difference between python range() and numpy arange()***

In [70]:
 # We will do one for negative values as well
print("Every 5th number from 50 in reverse order\n", np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


# linspace

In [71]:
print((np.linspace(1,5,50))) # Here 50 is the number of the it will generate in between starting point and end point

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


print((np.linspace(1,5,50))) Remember here 50 is not a step size, but the difference between anytwo number in that list is same

In [72]:
print((np.linspace(1,5,50, endpoint=False))) # This time the function is not ending on 5 like it did previously because of end point

[1.   1.08 1.16 1.24 1.32 1.4  1.48 1.56 1.64 1.72 1.8  1.88 1.96 2.04
 2.12 2.2  2.28 2.36 2.44 2.52 2.6  2.68 2.76 2.84 2.92 3.   3.08 3.16
 3.24 3.32 3.4  3.48 3.56 3.64 3.72 3.8  3.88 3.96 4.04 4.12 4.2  4.28
 4.36 4.44 4.52 4.6  4.68 4.76 4.84 4.92]


In [73]:
np.linspace(2.0, 3.0, num=5) # num=5 says that in output i want 5 elements

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [74]:
np.linspace(2.0, 3.0, num=5, endpoint=False) # I wont get the end value in this case

array([2. , 2.2, 2.4, 2.6, 2.8])

In [75]:
np.linspace(2.0, 3.0, num=5, retstep=True) # retstep prints the number of steps it has taken between two values

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

# Logspace
* **By default the base would be 10**

In [76]:
np.logspace(2.0, 3.0, num=4, base=10) # This gives us logrithmic differences

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [77]:
np.logspace(2.0, 3.0, num=4, endpoint=False) # end number wont be their

array([100.        , 177.827941  , 316.22776602, 562.34132519])

# Matrix creation

In [78]:
print(np.zeros((3,4))) # 3 rows and 4 columns

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [79]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [80]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [81]:
np.ones((3,4,5)) # here we have 3 (4,5) dimensional array

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [82]:
print(5+np.ones((3,5))) # 5 got added on every value of 1

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [83]:
np.empty((3,5)) #it gives previous array but if i restart my kernal it will give me any random value

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

The above line i wrote is before restarting my kernal next will be after restarting my kernal

In [84]:
import numpy as np
np.empty((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [85]:
# Identity Matrices
mat1 = np.eye(4)
mat1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Identity metrixes will always be a square**

Scalar in numpy is the data without the dimension while vector is the data with dimensions

Extract a diagonal or construct a diagonal array

In [88]:
x = np.arange(16).reshape((-1,4))

In [89]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Problems

* Create a (3,4,8) array with all ones and perform addition operation of 5 and than multiplication operation with 2? 
* Do the same thing with zeros.
* Generate 80 data between 4 to 8.
* Take a list and convert those list in metrixes
* Create an array of size (4x5x2) show me the dimesnion shape and data type of that array.
* Take two array both of (3,3,3) and add them.



In [130]:
a = (np.ones((3,4,8)) +5)*2
a

array([[[12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.]],

       [[12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.]],

       [[12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.],
        [12., 12., 12., 12., 12., 12., 12., 12.]]])

In [132]:
# Similarly for zeros
a = (np.zeros((3,4,8))+5)*2
a

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [133]:
# Generate 80 data between 4 to 8.
a = np.linspace(4,8,80, endpoint = False)
a

array([4.  , 4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ,
       4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  , 5.05,
       5.1 , 5.15, 5.2 , 5.25, 5.3 , 5.35, 5.4 , 5.45, 5.5 , 5.55, 5.6 ,
       5.65, 5.7 , 5.75, 5.8 , 5.85, 5.9 , 5.95, 6.  , 6.05, 6.1 , 6.15,
       6.2 , 6.25, 6.3 , 6.35, 6.4 , 6.45, 6.5 , 6.55, 6.6 , 6.65, 6.7 ,
       6.75, 6.8 , 6.85, 6.9 , 6.95, 7.  , 7.05, 7.1 , 7.15, 7.2 , 7.25,
       7.3 , 7.35, 7.4 , 7.45, 7.5 , 7.55, 7.6 , 7.65, 7.7 , 7.75, 7.8 ,
       7.85, 7.9 , 7.95])

In [106]:
# Take a list and convert those list in metrixes
a = [[2,3,4], [5,6,7], [8,9,10]]
b = np.array(a)

In [107]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [134]:
# Create an array of size (4x5x2) show me the dimesnion shape and data type of that array.
a = np.ones((4,5,2))
print(f" data type is {type(a)} and size is {a.size} and dimension is {a.ndim} and shape is {a.shape}")

 data type is <class 'numpy.ndarray'> and size is 40 and dimension is 3 and shape is (4, 5, 2)


In [126]:
# Take two array both of (3,3,3) and add them.
a = np.ones((3,3,3))
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [127]:
b = np.empty((3,3,3),float)
a+b

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])